apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podchaosmonkey

commonLabels:
  app.kubernetes.io/name: podchaosmonkey

images:
- name: podchaosmonkey
  newName: 192.168.39.96:5000/podchaosmonkey
  newTag: latest

resources:
- ./namespace.yaml
- ./deployment.yaml
- ./serviceaccount.yaml
